
all:
	dot graph-topology.gv -Teps > graph-topology.eps
	dot graph-topology-times.gv -Teps > graph-topology-times.eps
	dot graph-topology-distances.gv -Teps > graph-topology-distances.eps


clean:
	rm -rf *.eps
	rm -rf *.pdf
