@startuml


node "Node" {
  Application - Library
  Application - MPI
  Application - ESDM
  Library - ESDM
  ESDM - MPI
}


package "Some Group" {
    DomainDescription - ContainerFormat
    ContainerFormat - Index
    Index - ESDMShard
    ContainerFormat - ESDMShard
}


database StorageBackend {


  folder "Namespace" {
    [Directories and Files]
  }
  frame "Config" {
    [Topology]
    [Options]
  }
}


database Target1 {

}
database Target2 {

}


ESDM - DomainDescription

ESDMShard - StorageBackend



StorageBackend - Target1
StorageBackend - Target2



@enduml
